import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run before static files are deployed.
config :packetflow_chat_demo, PacketflowChatDemoWeb.Endpoint,
  url: [host: System.get_env("PHX_HOST") || "localhost", port: String.to_integer(System.get_env("PORT") || "4000")],
  http: [
    ip: {0, 0, 0, 0, 0, 0, 0, 0},
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to your endpoint configuration:
#
#     config :packetflow_chat_demo, PacketflowChatDemoWeb.Endpoint,
#       https: [
#         ...,
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SSL_KEYFILE"),
#         certfile: System.get_env("SSL_CERTFILE")
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/bandit/Bandit.html#t:options/0

# Do not print debug messages in production
config :logger, level: :info

# Runtime configuration is recommended, as it is simpler for important
# configuration such as the database and endpoint. For development, you
# can use the `config/dev.exs` file, which is loaded automatically
# by the `config/config.exs` file.

