version: '3.8'

services:
  packetflow-chat-demo:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - HOST=0.0.0.0
      - DEFAULT_MODEL=gpt-3.5-turbo
      - DEFAULT_TEMPERATURE=0.7
      - DEFAULT_MAX_TOKENS=1000
      - ENABLE_SIMULATION=true
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for session persistence in production
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped

# volumes:
#   redis_data:
