{application,packetflow,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"PacketFlow ADT Substrate: Intent-Context-Capability oriented algebraic data types"},
              {modules,['Elixir.PacketFlow.ADT',
                        'Elixir.PacketFlow.Application',
                        'Elixir.PacketFlow.Capability',
                        'Elixir.PacketFlow.Context','Elixir.PacketFlow.DSL',
                        'Elixir.PacketFlow.DSL.Capability',
                        'Elixir.PacketFlow.DSL.Context',
                        'Elixir.PacketFlow.DSL.Intent',
                        'Elixir.PacketFlow.DSL.Reactor',
                        'Elixir.PacketFlow.Effect','Elixir.PacketFlow.Intent',
                        'Elixir.PacketFlow.Reactor',
                        'Elixir.PacketFlow.Reactor.Message',
                        'Elixir.PacketFlow.Registry']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.PacketFlow.Application',[]}}]}.
